apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
commonLabels:
  env: staging
patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - cronjob-patch.yaml
