apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      env: prod
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: cronjob-patch.yaml
