apiVersion: batch/v1
kind: CronJob
metadata:
  name: temperature-storage-cronjob
  labels:
    app: hivebox-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            {{- include "common.podSecurityContext" . | nindent 12 }}
          initContainers:
            - name: wait-for-start
              image: {{ .Values.images.cronjob }}
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -eu
                  while true; do
                    if curl -sSf -m 3 http://hivebox-service/version >/dev/null; then
                      echo "Hivebox service is up!"
                      exit 0
                    else
                      echo "Waiting for Hivebox service to be available..."
                      sleep 5
                    fi
                  done
              securityContext:
                {{- include "common.containerSecurityContext" . | nindent 16 }}
              resources:
                {{- include "common.resources" (dict "Values" .Values "name" "cronjob") | nindent 16 }}
          containers:
            - name: temperature-storage
              image: {{ .Values.images.cronjob }}
              command: ["curl"]
              args:
                - "-f"
                - "-s"
                - "-S"
                - "--max-time"
                - "60"
                - "http://hivebox-service/store"
              securityContext:
                {{- include "common.containerSecurityContext" . | nindent 16 }}
              resources:
                {{- include "common.resources" (dict "Values" .Values "name" "cronjob") | nindent 16 }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
