name: hadolint
on: [push]

jobs:
  hadolint:
    runs-on: ubuntu-24.04
    name: Hadolint
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:  
          dockerfile: Dockerfile
