name: Hadolint

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  hadolint-linting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.2.0
        with:  
          dockerfile: Dockerfile