name: Hadolint

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-24.04
    name: Hadolint
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:  
          dockerfile: Dockerfile
