name: Terrascan IaC scanner

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terrascan
        uses: tenable/terrascan-action@v1.5.0
        with:
          iac_type: k8s
          iac_version: v1
          iac_dir: k8s
          policy_type: k8s
          verbose: true
          skip_rules: AC_K8S_0080
          only_warn: true