name: Terrascan IaC scanner

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: read
  security-events: write

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terrascan
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: k8s
          iac_version: v1
          iac_dir: k8s
          policy_type: k8s
          sarif_upload: true  # Upload results to GitHub Security tab
          
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan.sarif